version: "3.7"

services:
  fastapi:
    build:
      context: ./
      dockerfile: ./src/DockerfileWebApi
#    environment:
#      REDISSERVER: ${REDISSERVER}
#      C_FORCE_ROOT: "true"
    env_file:
      - ./src/app/env/dev.env
    ports:
      - "5000:80"
    depends_on:
      - redis_server

  worker:
    build:
      dockerfile: ./src/DockerfileCelery
      context: ./
    env_file:
      - ./src/app/env/dev.env
#    environment:
#      REDISSERVER: ${REDISSERVER}
#      C_FORCE_ROOT: "true"
    depends_on:
      - redis_server

  redis_server:
    image: redis

  flower:
    image: mher/flower
    env_file:
      - ./src/app/env/dev.env
    command: ["flower", "--broker=${REDISSERVER}", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - redis_server
