version: "3.7"

services:
  fastapi:
    build:
      context: ./
      dockerfile: ./src/DockerfileWebApi
    env_file:
      - ./src/app/env/dev.env
    ports:
      - "80:80"
    depends_on:
      - redis_server

  worker:
    build:
      dockerfile: ./src/DockerfileCelery
      context: ./
    env_file:
      - ./src/app/env/dev.env
    depends_on:
      - redis_server

  redis_server:
    image: redis

  flower:
    image: mher/flower
    env_file:
      - ./src/app/env/dev.env
    command: ["celery", "flower", "--broker=${REDISSERVER}", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - redis_server
      - worker
